on:
  push:
    branches: main
name: Apply clippy and PR changes
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: install lib
        run: sudo apt install libasound2-dev
      - run: rustup component add clippy
      - run: cargo clippy --fix -Z unstable-options --features vulkan
      - run: git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          commit-message: "style(lint): automatically applied clippy lint"
          title: "Automatic lint from clippy"

